[tool.poetry]
name = "teams-azure"
version = "0.0.0"
license = "MIT"
description = "Teams Azure"
authors = ["Microsoft <teams@microsoft.com>"]
readme = "README.md"
repository = "https://github.com/Microsoft/teams-ai"
keywords = ["microsoft", "teams", "bots", "ai"]
classifiers = [
    "Programming Language :: Python :: 3.8",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

packages = [
    { include = "teams/azure" }
]

[tool.poetry.dependencies]
python = ">=3.8.3,<4.0"
azure-cosmos = "3.2.0"
azure-storage-blob = "12.7.0"
azure-storage-queue = "12.1.5"
jsonpickle = "1.4"
teams-schema = { path = "../schema" }
teams-connector = { path = "../connector" }

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pylint = "^2.17.4"
pytest-cov = "^4.1.0"
pytest-asyncio = "^0.21.1"
aiounittest = "1.3.0"
black = "^23.7.0"
teams-core = { path = "../core" }
teams-testing = { path = "../testing", develop = true }

[tool.poetry.scripts]
lint = "scripts:lint"
fmt = "scripts:fmt"
test = "scripts:test"
clean = "scripts:clean"
ci = "scripts:ci"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py38']

[tool.pytest.ini_options]
addopts = "--cov-report html:coverage --cov=teams"