[tool.poetry]
name = "teams-schema"
version = "0.0.0"
license = "MIT"
description = "Teams Schema"
authors = ["Microsoft <teams@microsoft.com>"]
readme = "README.md"
repository = "https://github.com/Microsoft/teams-ai"
keywords = ["microsoft", "teams", "bots", "ai"]
classifiers = [
    "Programming Language :: Python :: 3.8",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

packages = [
    { include = "teams/schema" }
]

[tool.poetry.dependencies]
python = ">=3.8.3,<4.0"
msrest = "0.6.21"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pylint = "^2.17.4"
pytest-cov = "^4.1.0"
pytest-asyncio = "^0.21.1"
aiounittest = "1.3.0"
black = "^23.7.0"
teams-connector = { path = "../connector", develop = true }

[tool.poetry.scripts]
lint = "scripts:lint"
fmt = "scripts:fmt"
test = "scripts:test"
clean = "scripts:clean"
ci = "scripts:ci"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py38']

[tool.pytest.ini_options]
addopts = "--cov-report html:coverage --cov=teams"