[tool.poetry]
name = "teams-testing"
version = "0.0.0"
license = "MIT"
description = "Teams Testing"
authors = ["Microsoft <teams@microsoft.com>"]
readme = "README.md"
repository = "https://github.com/Microsoft/teams-ai"
keywords = ["microsoft", "teams", "bots", "ai"]
classifiers = [
    "Programming Language :: Python :: 3.8",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

packages = [
    { include = "teams/testing" }
]

[tool.poetry.dependencies]
python = ">=3.8.3,<4.0"
teams-core = { path = "../core" }
teams-schema = { path = "../schema" }
teams-dialogs = { path = "../dialogs" }
teams-azure = { path = "../azure" }

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pylint = "^2.17.4"
yapf = "^0.40.1"
pytest-cov = "^4.1.0"
pytest-asyncio = "^0.21.1"
aiounittest = "1.3.0"

[tool.poetry.scripts]
lint = "scripts:lint"
fmt = "scripts:fmt"
test = "scripts:test"
clean = "scripts:clean"
ci = "scripts:ci"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.yapf]
based_on_style = "pep8"
spaces_before_comment = 4
split_before_logical_operator = true

[tool.pytest.ini_options]
addopts = "--cov-report html:coverage --cov=teams"